### ISSUE TITLE
#4 SRS Documentation 

### ISSUE THREAD

**Issue by JunoJunho** [AutoDo/AutoDo#4]
We need to write Software Requirement Specification (SRS) of our AutoDo.

Assign to : @jin8 @3kd1000 @JunoJunho

**Comment by JunoJunho** [comment]
I assigned the ToDo inside the document to write derived textual requirement.
Check the Google Doc, and write your **ToDo.**
Maybe, you need to include the non-functional requirement inside the your assigned paragraph.

**Comment by jin8** [comment]
Add Use case diagram in

**Comment by JunoJunho** [comment]
We extend this documentation until a week before EOSP.
